export const FETCH_STATES_HISTORY = "FETCH_STATES_HISTORY";
export const FETCH_STATES_CURRENT = "FETCH_STATES_CURRENT";
export const FETCH_GEODATA = "FETCH_GEODATA";
export const LOADING_CURRENT_DATA = "LOADING_CURRENT_DATA";
export const FAILED_LOAD_CURRENT = "FAILED_LOAD_CURRENT";
export const FAILED_LOAD_HISTORY = "FAILED_LOAD_HISTORY";